HW_1
KonstantinOmm/python_advanced_hillel pull request #1
Opened 2022-08-20 12:46 UTC by KonstantinOmm

Home work 1. Students average marks

2022-08-22 10:07 UTC, python-hillel commented on src/HW_1/Home_1.py
> +    marks: list[int]
Python не видит тип list[int]. Он должен быть импортирован.

2022-08-22 10:08 UTC, python-hillel commented on src/HW_1/Home_1.py
> +from dataclasses import dataclass
Для чего Вам понадобился этот импорт?

2022-08-22 10:08 UTC, python-hillel commented on src/HW_1/Home_1.py
> +    marks: list[int]
Эти атрибуты должны быть атрибутами объекта(экземпляра), но не класса...

2022-08-22 10:11 UTC, python-hillel requested changes
Надо исправить или изменить Ваше решение.

2022-08-22 10:11 UTC, python-hillel commented on src/HW_1/Home_1.py
> +    main()
Применение класса не обязательно. Ну, или надо исправить.

2022-08-23 12:46 UTC, KonstantinOmm commented on src/HW_1/Home_1.py
> +from dataclasses import dataclass
Для того, чтобы импортировать декоратор @dataclass, который упрощает этот код 
class Student:
    def __init__(self, first_name, last_name, marks):
        self.first_name = first_name
        self.last_name = last_name
        self.marks = marks

до того что я написал:
class Student:
    first_name: str
    last_name: str
    marks: list[int]

2022-08-24 12:52 UTC, python-hillel approved these changes

2022-08-24 19:15 UTC, merged